---
title: "DataZoom Amazonia"
author: "DataZoom Team"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Useful Sources

This document is written based on the following materials:

- R Packages, Wickham, H. & Bryan, J. Available at \url{https://r-pkgs.org/} - PCKG_R

- Tidyverse Style Guide, Wickham, H. Available at \url{https://style.tidyverse.org/} - TIDY_STYLE

- Grant McDermott's Data Science for Economists Lecture Notes (PhD, University of Oregon). Available at \url{https://github.com/uo-ec607/lectures} - GRANT_DS_ECON

- Advanced R, Wickham, H. Available at \url{https://adv-r.hadley.nz/} - ADV_R

- R for Data Science, Tidyverse Team. Available at \url{https://r4ds.had.co.nz/} - R4DS

## DataZoom Amazonia Package Objectives

(Include Description, Goals, Similar Packages, Differentials -- anything that help us set out the final product we want to deliver)

## Functions Objectives

(Describe clearly what each function should do in generic terms. This should act as the main direction on how to write harmonized functions between different team members and heavily use the materials above.)



## Current Functions

For each function, include description and links of data sources, try to run examples and set possible margins for adjustments.

### Comex

### Degrad

### Deter

### IPS

### MapBiomas

### Municipios

### PAM

### Prodes

### SigMine
