---
title: "Google Earth Engine Interface"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Google Earth Engine Interface}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Google Earth Engine

This function provides a wrapper for the \code{r-spatial/rgee} interface for [Google Earth Engine](https://earthengine.google.com/), with an emphasis on building panel data for brazilian geometries.

The function currently supports VIIRS Nighlights, but datasets will be added.

(TO-DO: Write more)

## Usage

You can use the function to construct panel data:

```{r use,eval=FALSE}
library(datazoom.amazonia)
df = load_earth_engine(db = 'NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG',state=c('RJ','SP'))
head(df)
```

And then plot cool stuff:

```{r plot,eval=FALSE}

ggplot2::ggplot() + 
  hrbrthhemes::theme_modern_rc() + 
  ggplot2::geom_sf(data = sf::st_as_sf(df[df$year==2014,]),ggplot2::aes(fill = mean_rad),col=NA) +
  viridis::scale_fill_viridis_c(option='B')


```



