---
title: "IMAZON"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{IMAZON}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Loads data categorizing each municipality by the level of deforestation pressure faced it faces. The categories used by Imazon have three levels, ranging from 0 to 3.

There are four parameters in this function:

```
  1. dataset:
  # "imazon_shp" includes the municipalities shapefiles and the deforestation category according to imazon
  2. raw_data: there is one option:
  # TRUE, as imazon already delivers organized data.
  
  3. geo_level:
  # "municipality". The data is only available at the municipality level.
  
  4. language: you can choose between portuguese ('pt') and english ('eng')
  
  
```

```{r eval=FALSE}
# Download data
data <- load_imazon(dataset = "imazon_shp", raw_data = TRUE,
                     geo_level = "municipality", language = "pt")
```
