---
title: "Social Progress Index"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Social Progress Index}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## The Dataset

The Amazon Social Progress Index, an initiative from Imazon with support from 
the Social Progress Imperative is an index that measures the social and environmental progress of its locations. Namely, the 772 municipalities in the Amazon region.


## Usage

To download and compile data on the index for 2014 and 2018, just run the function `load_ips`.

```{r, eval = FALSE}
library(datazoom.amazonia)

# Download raw data (raw_data = TRUE) from 2014 (time_period = 2014)
data <- load_ips(dataset = "ips", raw_data = TRUE, time_period = 2014)

# Download treated data (raw_data = FALSE) from 2018 
# (time_period = 2018) in portuguese (language = 'pt')
data <- load_ips(dataset = "ips", raw_data = FALSE,
                 time_period = 2018, language = 'pt')
```

