#' @title Greenhouse gases emission estimates (SEEG)
#'
#' Loads data of estimates of emission of greenhouse gases of Brazilian cities
#'
#'@param language A \code{string} that indicates in which language the data will be returned. The default is "pt", so your data will be returned in Portuguese. Currently, only Portuguese and English are supported.
#'
#' @return A \code{data frame}.
#'
#' @author DataZoom, Department of Economics, Pontifical Catholic University of Rio de Janeiro
#'
#' @encoding UTF-8
#'
#' @export load_seeg
#'
#' @examples \dontrun{datazoom.amazonia::load_seeg()}
#'

load_seeg <- function(language = "pt"){
  message("Function requires download of large file, so it may take time to run")

  if (language != "pt" && language != "eng"){
    warning("Language selected not supported! Proceding with Portuguese")
    language = "pt"
  }

  direc <- getwd()
  url <- "https://drive.google.com/file/d/1rUc6H8BVKT9TH-ri6obzHVt7WI1eGUzd/view?usp=sharing"
  urlteste <- "https://drive.google.com/file/d/1A_neQegigQuDvGHfpngk_11wsqGyR8US/view?usp=sharing"

  df <- gsheet::gsheet2tbl(urlteste)
  df <- janitor::clean_names(df)

  #stringi::stri_escape_unicode()
  df <- as.data.frame(gsub("\u00ed", "i", as.matrix(df)))
  df <- as.data.frame(gsub("\u00f5", "o", as.matrix(df)))
  df <- as.data.frame(gsub("\u00e1", "a", as.matrix(df)))
  df <- as.data.frame(gsub("\u00e7", "c", as.matrix(df)))
  df <- as.data.frame(gsub("\u00e3", "a", as.matrix(df)))
  df <- as.data.frame(gsub("\u00c1", "A", as.matrix(df)))
  df <- as.data.frame(gsub("\u00e9", "e", as.matrix(df)))
  df <- as.data.frame(gsub("\u00fa", "u", as.matrix(df)))
  df <- as.data.frame(gsub("\u00f4", "o", as.matrix(df)))
  df <- as.data.frame(gsub("\u00f3", "o", as.matrix(df)))
  df <- as.data.frame(gsub("\u00e2", "a", as.matrix(df)))
  df <- as.data.frame(gsub("\u00d3", "O", as.matrix(df)))
  df <- as.data.frame(gsub("\u00ea", "e", as.matrix(df)))

  to_english <- function(df){
    index <- df$`Tier 1` == "Agropeacuaria"
    df$`Tier 1`[index] <- "agricultura and cattle raising"
    index <- df$`Tier 1` == "Energia"
    df$`Tier 1`[index] <- "Energy"
    index <- df$`Tier 1` == "Mudança de Uso da Terra e Florestas"
    df$`Tier 1`[index] <- "Changes in land and forrest use"
    index <- df$`Tier 1` == "Processos Industriais"
    df$`Tier 1`[index] <- "industrial processes"
    index <- df$`Tier 1` == "Residuos"
    df$`Tier 1`[index] <- "residues"
    ## TIER 2##
    index <- df$`Tier 2` == "Alteracoes de Uso do Solo"
    df$`Tier 2`[index] <- "Changes in Land use"
    index <- df$`Tier 2` == "Cultivo de Arroz"
    df$`Tier 2`[index] <- "Rice growing"
    index <- df$`Tier 2` == "Efluentes Liquidos"
    df$`Tier 2`[index] <- "Liquid effluents"
    index <- df$`Tier 2` == "Emissoes de HFCs"
    df$`Tier 2`[index] <- "HFC emissions"
    index <- df$`Tier 2` == "Emissoes Fugitivas"
    df$`Tier 2`[index] <- "Fugitive emissions"
    index <- df$`Tier 2` == "Emissoes pela Queima de Combustiveis"
    df$`Tier 2`[index] <- "Emissions by fuel combustion"
    index <- df$`Tier 2` == "Fermentacao Enterica"
    df$`Tier 2`[index] <- "Enteric fermentation"
    index <- df$`Tier 2` == "Industria Quimica"
    df$`Tier 2`[index] <- "Chemical industry"
    index <- df$`Tier 2` == "Manejo de Dejetos Animais"
    df$`Tier 2`[index] <- "Animal waste handling"
    index <- df$`Tier 2` == "Producao de metais"
    df$`Tier 2`[index] <- "Metal production"
    index <- df$`Tier 2` == "Produtos minerais"
    df$`Tier 2`[index] <- "Mineral products"
    index <- df$`Tier 2` == "Queima de residuos agricolas"
    df$`Tier 2`[index] <- "agricultural residue combustion"
    index <- df$`Tier 2` == "Remocao em areas protegidas"
    df$`Tier 2`[index] <- "removal in protected areas"
    index <- df$`Tier 2` == "Remocao por Mudanaa de Uso da Terra"
    df$`Tier 2`[index] <- "removal by changes in Land use"
    index <- df$`Tier 2` == "Remocao por Vegetacao Secundaria"
    df$`Tier 2`[index] <- "Removal by secondary vegetation"
    index <- df$`Tier 2` == "Residuos Florestais"
    df$`Tier 2`[index] <- "Forrest residues"
    index <- df$`Tier 2` == "Residuos Solidos"
    df$`Tier 2`[index] <- "Solid residues"
    index <- df$`Tier 2` == "Solos Manejados"
    df$`Tier 2`[index] <- "Handled soils"
    index <- df$`Tier 2` == "Uso de SF6"
    df$`Tier 2`[index] <- "SF6 use"
    index <- df$`Tier 2` == "Uso Nao-Energetico de Combusteveis e Uso de Solventes"
    df$`Tier 2`[index] <- "Non-energetic fuel use and solvent use"
    ##TIER 3##
    index <- df$`Tier 3` == "Agropecuario"
    df$`Tier 3`[index] <- "agriculture and cattle raising "
    index <- df$`Tier 3` == "Amazonia"
    df$`Tier 3`[index] <- "Amazon"
    index <- df$`Tier 3` == "Consumo de Barrilha"
    df$`Tier 3`[index] <- "Soda ash consumption"
    index <- df$`Tier 3` == "Consumo Final Nao Energetico"
    df$`Tier 3`[index] <- "Final non-energetic consumption"
    index <- df$`Tier 3` == "Diretas"
    df$`Tier 3`[index] <- "Direct"
    index <- df$`Tier 3` == "Disposicao Final"
    df$`Tier 3`[index] <- "Final disposal"
    index <- df$`Tier 3` == "Efluentes Liquidos Domesticos"
    df$`Tier 3`[index] <- "Domestic liquid effluents"
    index <- df$`Tier 3` == "Efluentes Liquidos Industriais"
    df$`Tier 3`[index] <- "Industrial liquid effluents"
    index <- df$`Tier 3` == "Equipamentos Eletricos"
    df$`Tier 3`[index] <- "Electrical equipment"
    index <- df$`Tier 3` == "Geracao de Eletricidade (Servico Publico)"
    df$`Tier 3`[index] <- "Electricity generation (public service)"
    index <- df$`Tier 3` == "Incineracao ou queima a ceu aberto"
    df$`Tier 3`[index] <- "Incineration or open-air burning"
    index <- df$`Tier 3` == "Indiretas"
    df$`Tier 3`[index] <- "indirect"
    index <- df$`Tier 3` == "Producao de Acido Adipico"
    df$`Tier 3`[index] <- "adipic acid production"
    index <- df$`Tier 3` == "Producao de Acido Fosforico"
    df$`Tier 3`[index] <- "Fosforic acid production"
    index <- df$`Tier 3` == "Producao de Acido Nitrico"
    df$`Tier 3`[index] <- "nitric acid production"
    index <- df$`Tier 3` == "Producao de Acrilonitrila"
    df$`Tier 3`[index] <- "acrylonitrile production"
    index <- df$`Tier 3` == "Producao de Aluminio"
    df$`Tier 3`[index] <- "aluminum production"
    index <- df$`Tier 3` == "Producao de Amonia"
    df$`Tier 3`[index] <- "ammonium production"
    index <- df$`Tier 3` == "Producao de Cal"
    df$`Tier 3`[index] <- "lime production"
    index <- df$`Tier 3` == "Producao de Caprolactama"
    df$`Tier 3`[index] <- "caprolactam production"
    index <- df$`Tier 3` == "Producao de Carbureto de Calcio"
    df$`Tier 3`[index] <- "calcium carbide production"
    index <- df$`Tier 3` == "Producao de Cimento"
    df$`Tier 3`[index] <- "ciment production"
    index <- df$`Tier 3` == "Producao de Cloreto de Vinila"
    df$`Tier 3`[index] <- "Vinyl chloride production"
    index <- df$`Tier 3` == "Producao de Combustiveis"
    df$`Tier 3`[index] <- "fuel production"
    index <- df$`Tier 3` == "Producao de Coque de Petroleo Calcinado"
    df$`Tier 3`[index] <- "calcinated petroleum coke production"
    index <- df$`Tier 3` == "Producao de Eteno"
    df$`Tier 3`[index] <- "ethylene production"
    index <- df$`Tier 3` == "Producao de Ferro Gusa e Aco"
    df$`Tier 3`[index] <- "pig iron and steel production"
    index <- df$`Tier 3` == "Producao de Ferrovias"
    df$`Tier 3`[index] <- "Railroad production"
    index <- df$`Tier 3` == "Producao de Magnesio"
    df$`Tier 3`[index] <- "magnesium production"
    index <- df$`Tier 3` == "Produção de Metanol"
    df$`Tier 3`[index] <- "methanol production"
    index <- df$`Tier 3` == "Producao de Negro-de-fumo"
    df$`Tier 3`[index] <- "carbon black production"
    index <- df$`Tier 3` == "Producao de Outros Nao-Ferrosos"
    df$`Tier 3`[index] <- "other non-ferrous production"
    index <- df$`Tier 3` == "Producao de Oxido de Eteno"
    df$`Tier 3`[index] <- "ethylene oxide production"
    index <- df$`Tier 3` == "Producao de Vidro "
    df$`Tier 3`[index] <- "glass production"
    index <- df$`Tier 3` == "Publico"
    df$`Tier 3`[index] <- "public"
    index <- df$`Tier 3` == "Residencial"
    df$`Tier 3`[index] <- "residential"
    index <- df$`Tier 3` == "Transportes"
    df$`Tier 3`[index] <- "transport"
    index <- df$`Tier 3` == "Tratamento Biologico de Residuos Solidos"
    df$`Tier 3`[index] <- "Biologic treatment of solid residues"
    ## TIER 4##
    index <- df$`Tier 4` == "Aereo"
    df$`Tier 4`[index] <- "Aerial"
    index <- df$`Tier 4` == "Alimentos e bebidas"
    df$`Tier 4`[index] <- "Food and beverage"
    index <- df$`Tier 4` == "Aplicacao de residuos organicos"
    df$`Tier 4`[index] <- "organic residue application"
    index <- df$`Tier 4` == "Cal Calcitica"
    df$`Tier 4`[index] <- "calcium lime"
    index <- df$`Tier 4` == "Cal Dolomitica"
    df$`Tier 4`[index] <- "dolomitic lime"
    index <- df$`Tier 4` == "Cal Magnesiana"
    df$`Tier 4`[index] <- "magnesium lime"
    index <- df$`Tier 4` == "Ceramica"
    df$`Tier 4`[index] <- "ceramic"
    index <- df$`Tier 4` == "Cimento"
    df$`Tier 4`[index] <- "ciment"
    index <- df$`Tier 4` == "Consumo de Calcario"
    df$`Tier 4`[index] <- "limestone consumption"
    index <- df$`Tier 4` == "Consumo de Combustiveis Redutores"
    df$`Tier 4`[index] <- "fuel reducers consumption"
    index <- df$`Tier 4` == "Consumo de Dolomita"
    df$`Tier 4`[index] <- "dolomite consumption"
    index <- df$`Tier 4` == "Consumo em Outros Setores"
    df$`Tier 4`[index] <- "consumption in other sectors"
    index <- df$`Tier 4` == "Deposicao Atmosferica"
    df$`Tier 4`[index] <- "atmosferic deposition"
    index <- df$`Tier 4` == "Deposicao de dejetos em pastagem"
    df$`Tier 4`[index] <- "deposition of pasture excrements"
    index <- df$`Tier 4` == "em Area Protegida"
    df$`Tier 4`[index] <- "in protected area"
    index <- df$`Tier 4` == "Exploracao de petroleo e gas natural"
    df$`Tier 4`[index] <- "exploration of petroleum and natural gas"
    index <- df$`Tier 4` == "Ferro gusa e aco"
    df$`Tier 4`[index] <- "pig iron and steel"
    index <- df$`Tier 4` == "Ferro Ligas"
    df$`Tier 4`[index] <- "iron alloy"
    index <- df$`Tier 4` == "Ferroviario"
    df$`Tier 4`[index] <- "railway"
    index <- df$`Tier 4` == "Fertilizantes Sinteticos"
    df$`Tier 4`[index] <- "sinthetic fertilizers"
    index <- df$`Tier 4` == "fora de Area Protegida"
    df$`Tier 4`[index] <- "outside of protected area"
    index <- df$`Tier 4` == "Hidroviario"
    df$`Tier 4`[index] <- "waterway"
    index <- df$`Tier 4` == "Incineracao"
    df$`Tier 4`[index] <- "incineration"
    index <- df$`Tier 4` == "Lixiviacao"
    df$`Tier 4`[index] <- "leaching"
    index <- df$`Tier 4` == "Lodo de ETE"
    df$`Tier 4`[index] <- "ETE sludge"
    index <- df$`Tier 4` == "Mineracao e pelotizacao"
    df$`Tier 4`[index] <- "mining and pelletization"
    index <- df$`Tier 4` == "Mineralizacao de N associado a perda de C no solo"
    df$`Tier 4`[index] <- "mineralization of N Associated to the loss of C in the soil"
    index <- df$`Tier 4` == "Nao ferrosos e outros da metalurgia"
    df$`Tier 4`[index] <- "non-ferrous and others from metallurgy"
    index <- df$`Tier 4` == "Outras indústrias"
    df$`Tier 4`[index] <- "other industries"
    index <- df$`Tier 4` == "Outros"
    df$`Tier 4`[index] <- "other"
    index <- df$`Tier 4` == "Papel e celulose"
    df$`Tier 4`[index] <- "paper and cellulose"
    index <- df$`Tier 4` == "Producao de alcool"
    df$`Tier 4`[index] <- "alcohol production"
    index <- df$`Tier 4` == "Producao de Carne Avicola"
    df$`Tier 4`[index] <- "poultry meat production"
    index <- df$`Tier 4` == "Producao de Carne Bovina"
    df$`Tier 4`[index] <- "bovina meat production"
    index <- df$`Tier 4` == "Producao de Carne Suina"
    df$`Tier 4`[index] <- "swine meat production"
    index <- df$`Tier 4` == "Producao de carvao mineral e outros"
    df$`Tier 4`[index] <- "mineral coal production and other"
    index <- df$`Tier 4` == "Producao de carvao vegetal"
    df$`Tier 4`[index] <- "charcoal production"
    index <- df$`Tier 4` == "Producao de Celulose"
    df$`Tier 4`[index] <- "cellulose production"
    index <- df$`Tier 4` == "Producao de Cerveja"
    df$`Tier 4`[index] <- "beer production"
    index <- df$`Tier 4` == "Producao de Leite Cru"
    df$`Tier 4`[index] <- "raw milk production"
    index <- df$`Tier 4` == "Producao de Leite Pasteurizado"
    df$`Tier 4`[index] <- "pasteurized milk production"
    index <- df$`Tier 4` == "Producao de Queima de Residuos a Ceu Aberto"
    df$`Tier 4`[index] <- "open-air residue incineration production"
    index <- df$`Tier 4` == "Quimica"
    df$`Tier 4`[index] <- "chemistry"
    index <- df$`Tier 4` == "Refino de petroleo"
    df$`Tier 4`[index] <- "oil refinery"
    index <- df$`Tier 4` == "Residuos Agricolas"
    df$`Tier 4`[index] <- "agricultural residues"
    index <- df$`Tier 4` == "Residuos de servicos de saude"
    df$`Tier 4`[index] <- "Health services residues"
    index <- df$`Tier 4` == "Residuos Solidos Urbanos"
    df$`Tier 4`[index] <- "solid urban residues"
    index <- df$`Tier 4` == "Rodoviario"
    df$`Tier 4`[index] <- "Road traffic"
    index <- df$`Tier 4` == "Solos organicos"
    df$`Tier 4`[index] <- "organic soil"
    index <- df$`Tier 4` == "Tecnologia Prebaked Anode"
    df$`Tier 4`[index] <- "anode prebaked technology"
    index <- df$`Tier 4` == "Tecnologia Soderberg"
    df$`Tier 4`[index] <- "Soderberg technology"
    index <- df$`Tier 4` == "Textil"
    df$`Tier 4`[index] <- "textile"
    index <- df$`Tier 4` == "Transporte de gas natural"
    df$`Tier 4`[index] <- "natural gas transport"
    index <- df$`Tier 4` == "Uso de SF6"
    df$`Tier 4`[index] <- "SF6 use"
    ##TIER 5##
    index <- df$`Tier 5` == "Alcatrao"
    df$`Tier 5`[index] <- "Tar"
    index <- df$`Tier 5` == "Alcool hidratado"
    df$`Tier 5`[index] <- "hidrated alcohol"
    index <- df$`Tier 5` == "Bagaço de cana"
    df$`Tier 5`[index] <- "sugarcane bagasse"
    index <- df$`Tier 5` == "Carvao mineral"
    df$`Tier 5`[index] <- "mineral coal"
    index <- df$`Tier 5` == "Carvao vapor 3100"
    df$`Tier 5`[index] <- "coal vapor 3100"
    index <- df$`Tier 5` == "Carvao vapor 3300"
    df$`Tier 5`[index] <- "coal vapor 3300"
    index <- df$`Tier 5` == "Carvao vapor 3700"
    df$`Tier 5`[index] <- "coal vapor 3700"
    index <- df$`Tier 5` == "Carvao vapor 4200"
    df$`Tier 5`[index] <- "coal vapor 4200"
    index <- df$`Tier 5` == "Carvao vapor 4500"
    df$`Tier 5`[index] <- "coal vapor 4500"
    index <- df$`Tier 5` == "Carvao vapor 4700"
    df$`Tier 5`[index] <- "coal vapor 4700"
    index <- df$`Tier 5` == "Carvao vapor 5200"
    df$`Tier 5`[index] <- "coal vapor 5200"
    index <- df$`Tier 5` == "Carvao vapor 5900"
    df$`Tier 5`[index] <- "coal vapor 5900"
    index <- df$`Tier 5` == "Carvao vapor 6000"
    df$`Tier 5`[index] <- "coal vapor 6000"
    index <- df$`Tier 5` == "Carvao vapor sem especificacao"
    df$`Tier 5`[index] <- "coal vapor with no especification"
    index <- df$`Tier 5` == "Carvao vegetal"
    df$`Tier 5`[index] <- "charcoal"
    index <- df$`Tier 5` == "Compostagem"
    df$`Tier 5`[index] <- "composting"
    index <- df$`Tier 5` == "Consumo de Combustiveis Fosseis"
    df$`Tier 5`[index] <- "fossil fuel consumption"
    index <- df$`Tier 5` == "Consumo de Combustiveis Renovaveis"
    df$`Tier 5`[index] <- "renewable fuel consumption"
    index <- df$`Tier 5` == "Coque de carvao mineral"
    df$`Tier 5`[index] <- "mineral coal coke"
    index <- df$`Tier 5` == "Coque de petroleo"
    df$`Tier 5`[index] <- "petroleum coke"
    index <- df$`Tier 5` == "Desmatamento"
    df$`Tier 5`[index] <- "deforestation"
    index <- df$`Tier 5` == "Diesel de petroleo"
    df$`Tier 5`[index] <- "petroleum diesel"
    index <- df$`Tier 5` == "Gas canalizado RJ"
    df$`Tier 5`[index] <- "RJ canalized gas"
    index <- df$`Tier 5` == "Gas canalizado SP"
    df$`Tier 5`[index] <- "SP canalized gas"
    index <- df$`Tier 5` == "Gas de refinaria"
    df$`Tier 5`[index] <- "refinery gas"
    index <- df$`Tier 5` == "Gas natural"
    df$`Tier 5`[index] <- "natural gas"
    index <- df$`Tier 5` == "Gas natural seco"
    df$`Tier 5`[index] <- "dry natural gas"
    index <- df$`Tier 5` == "Gas natural umido"
    df$`Tier 5`[index] <- "humid natural gas"
    index <- df$`Tier 5` == "Gasolina automotiva"
    df$`Tier 5`[index] <- "automotive gasoline"
    index <- df$`Tier 5` == "Gasolina C"
    df$`Tier 5`[index] <- "gasoline C"
    index <- df$`Tier 5` == "Gasolina de aviacao"
    df$`Tier 5`[index] <- "Aviation gasoline"
    index <- df$`Tier 5` == "Lenha"
    df$`Tier 5`[index] <- "firewood"
    index <- df$`Tier 5` == "Lenha carvoejamento"
    df$`Tier 5`[index] <- "firewood in coal production"
    index <- df$`Tier 5` == "Lixivia"
    df$`Tier 5`[index] <- "bleach"
    index <- df$`Tier 5` == "Lubrificantes"
    df$`Tier 5`[index] <- "lubrificant"
    index <- df$`Tier 5` == "Nafta"
    df$`Tier 5`[index] <- "naphtha"
    index <- df$`Tier 5` == "Oleo combustivel"
    df$`Tier 5`[index] <- "fuel oil"
    index <- df$`Tier 5` == "Oleo diesel"
    df$`Tier 5`[index] <- "diesel oil"
    index <- df$`Tier 5` == "Outras biomassas"
    df$`Tier 5`[index] <- "other biomasses"
    index <- df$`Tier 5` == "Outras Mudancas de uso da terra"
    df$`Tier 5`[index] <- "other changes in land use"
    index <- df$`Tier 5` == "Outras nao renovaveis"
    df$`Tier 5`[index] <- "other non renewables"
    index <- df$`Tier 5` == "Outros"
    df$`Tier 5`[index] <- "other"
    index <- df$`Tier 5` == "Outros energeticos de petroleo"
    df$`Tier 5`[index] <- "other petroleum energeticals"
    index <- df$`Tier 5` == "Petroleo"
    df$`Tier 5`[index] <- "petroleum"
    index <- df$`Tier 5` == "Petroleo e gas natural"
    df$`Tier 5`[index] <- "natural gas and petroleum"
    index <- df$`Tier 5` == "Querosene de aviacao"
    df$`Tier 5`[index] <- "Aviation kerosene"
    index <- df$`Tier 5` == "Querosene iluminante"
    df$`Tier 5`[index] <- "iluminating kerosene"
    index <- df$`Tier 5` == "Regeneracao"
    df$`Tier 5`[index] <- "regeneration"
    index <- df$`Tier 5` == "Residuos de Servicos de Saude"
    df$`Tier 5`[index] <- "Health services residues"
    index <- df$`Tier 5` == "Residuos Solidos Urbanos"
    df$`Tier 5`[index] <- "solid urban residues"
    index <- df$`Tier 5` == "Vegetacao nativa estavel"
    df$`Tier 5`[index] <- "stable native vegetation"
    ##TIER 6##
    index <- df$`Tier 6` == "Aeronaves"
    df$`Tier 6`[index] <- "aircrafts"
    index <- df$`Tier 6` == "Algodao"
    df$`Tier 6`[index] <- "cotton"
    index <- df$`Tier 6` == "Aplicacao de Ureia"
    df$`Tier 6`[index] <- "Urea application"
    index <- df$`Tier 6` == "Area sem vegetacao -- Floresta secundaria"
    df$`Tier 6`[index] <- "area without vegetation -- secondary forrest"
    index <- df$`Tier 6` == "Area sem vegetacao -- Silvicultura"
    df$`Tier 6`[index] <- "area without vegetation -- silviculture"
    index <- df$`Tier 6` == "Area sem vegetacao -- Uso agropecuario"
    df$`Tier 6`[index] <- "area without vegetation -- agricultural and cattle raising use"
    index <- df$`Tier 6` == "Area sem vegetacao -- Vegetacao nao florestal secundaria"
    df$`Tier 6`[index] <- "area without vegetation -- non secondary forrest vegetation"
    index <- df$`Tier 6` == "Arroz"
    df$`Tier 6`[index] <- "rice"
    index <- df$`Tier 6` == "Asinino"
    df$`Tier 6`[index] <- "asinine"
    index <- df$`Tier 6` == "Automoveis"
    df$`Tier 6`[index] <- "automobiles"
    index <- df$`Tier 6` == "Aves"
    df$`Tier 6`[index] <- "birds"
    index <- df$`Tier 6` == "Bubalino"
    df$`Tier 6`[index] <- "buffalo"
    index <- df$`Tier 6` == "Caminhoes"
    df$`Tier 6`[index] <- "trucks"
    index <- df$`Tier 6` == "Cana-de-acucar"
    df$`Tier 6`[index] <- "sugarcane"
    index <- df$`Tier 6` == "Caprino"
    df$`Tier 6`[index] <- "goat"
    index <- df$`Tier 6` == "Carvoarias"
    df$`Tier 6`[index] <- "charcoal producers"
    index <- df$`Tier 6` == "Centrais Eletricas Autoprodutoras"
    df$`Tier 6`[index] <- "power plants autoproducers"
    index <- df$`Tier 6` == "Centrais Eletricas de Servico Publico"
    df$`Tier 6`[index] <- "power plants of public services"
    index <- df$`Tier 6` == "Comerciais Leves"
    df$`Tier 6`[index] <- "light commercials"
    index <- df$`Tier 6` == "Consumo Final Energetico"
    df$`Tier 6`[index] <- "final energetic consumption"
    index <- df$`Tier 6` == "Embarcacaes"
    df$`Tier 6`[index] <- "vessels"
    index <- df$`Tier 6` == "Equino"
    df$`Tier 6`[index] <- "equine"
    index <- df$`Tier 6` == "Feijao"
    df$`Tier 6`[index] <- "beans"
    index <- df$`Tier 6` == "Fertilizantes sinteticos"
    df$`Tier 6`[index] <- "sinthetic fertilizers"
    index <- df$`Tier 6` == "Floresta primaria -- Area sem vegetacao"
    df$`Tier 6`[index] <- "primary forrest --  area without vegetation"
    index <- df$`Tier 6` == "Floresta primaria -- Floresta primaria"
    df$`Tier 6`[index] <- "primary forrest --  primary forrest"
    index <- df$`Tier 6` == "Floresta primaria -- Silvicultura"
    df$`Tier 6`[index] <- "primary forrest --  silviculture"
    index <- df$`Tier 6` == "Floresta primaria -- Uso agropecuario"
    df$`Tier 6`[index] <- "primary forrest --  agricultural and cattle raising use"
    index <- df$`Tier 6` == "Floresta secundaria -- Area sem vegetacao"
    df$`Tier 6`[index] <- "secondary forrest -- area without vegetation"
    index <- df$`Tier 6` == "Floresta secundaria -- Floresta secundaria"
    df$`Tier 6`[index] <- "secondary forrest --  secondary forrest"
    index <- df$`Tier 6` == "Floresta secundaria -- Silvicultura"
    df$`Tier 6`[index] <- "secondary forrest -- silviculture"
    index <- df$`Tier 6` == "Floresta secundaria -- Uso agropecuario"
    df$`Tier 6`[index] <- "secondary forrest --  agricultural and cattle raising use"
    index <- df$`Tier 6` == "Gado de corte"
    df$`Tier 6`[index] <- "meat cattle"
    index <- df$`Tier 6` == "Gado de Leite"
    df$`Tier 6`[index] <- "milk cattle"
    index <- df$`Tier 6` == "Locomotivas"
    df$`Tier 6`[index] <- "locomotives"
    index <- df$`Tier 6` == "Mandioca"
    df$`Tier 6`[index] <- "cassava"
    index <- df$`Tier 6` == "Milho"
    df$`Tier 6`[index] <- "corn"
    index <- df$`Tier 6` == "Motocicletas"
    df$`Tier 6`[index] <- "motorcycles"
    index <- df$`Tier 6` == "Muar"
    df$`Tier 6`[index] <- "hinnies"
    index <- df$`Tier 6` == "Onibus"
    df$`Tier 6`[index] <- "buses"
    index <- df$`Tier 6` == "Outras culturas"
    df$`Tier 6`[index] <- "other cultures"
    index <- df$`Tier 6` == "Outros"
    df$`Tier 6`[index] <- "other"
    index <- df$`Tier 6` == "Ovino"
    df$`Tier 6`[index] <- "sheep"
    index <- df$`Tier 6` == "Pastagem"
    df$`Tier 6`[index] <- "pasture"
    index <- df$`Tier 6` == "Silvicultura -- Area sem vegetacao"
    df$`Tier 6`[index] <- "silviculture -- area without vegetation"
    index <- df$`Tier 6` == "Silvicultura -- Floresta secundaria"
    df$`Tier 6`[index] <- "silviculture -- secondary forrest"
    index <- df$`Tier 6` == "Silvicultura -- Uso agropecuario"
    df$`Tier 6`[index] <- "silviculture -- agricultural and cattle raising use"
    index <- df$`Tier 6` == "Silvicultura -- Vegetacao nao florestal secundaria"
    df$`Tier 6`[index] <- "silviculture -- non secondary forrest vegetation"
    index <- df$`Tier 6` == "Soja"
    df$`Tier 6`[index] <- "soy"
    index <- df$`Tier 6` == "Solos organicos"
    df$`Tier 6`[index] <- "organic soils"
    index <- df$`Tier 6` == "Suinos"
    df$`Tier 6`[index] <- "swine"
    index <- df$`Tier 6` == "Residuos"
    df$`Tier 6`[index] <- "residues"
    index <- df$`Tier 6` == "Torta de Filtro"
    df$`Tier 6`[index] <- "cake filter"
    index <- df$`Tier 6` == "Trigo"
    df$`Tier 6`[index] <- "wheat"
    index <- df$`Tier 6` == "Uso agropecuario -- Area sem vegetacao"
    df$`Tier 6`[index] <- "agricultural and cattle raising use --  area without vegetation"
    index <- df$`Tier 6` == "Uso agropecuario -- Floresta secundaria"
    df$`Tier 6`[index] <- "agricultural and cattle raising use -- secondary forrest"
    index <- df$`Tier 6` == "Uso agropecuario -- Silvicultura"
    df$`Tier 6`[index] <- "agricultural and cattle raising use -- silviculture"
    index <- df$`Tier 6` == "Uso agropecuario -- uso agropecuario"
    df$`Tier 6`[index] <- "agricultural and cattle raising use -- agricultural and cattle raising use"
    index <- df$`Tier 6` == "Uso agropecuario -- Vegetacao nao florestal secundaria"
    df$`Tier 6`[index] <- "agricultural and cattle raising use -- non secondary forrest vegetation"
    index <- df$`Tier 6` == "Uso de Calcario"
    df$`Tier 6`[index] <- "limestone use"
    index <- df$`Tier 6` == "Vegetacao nao florestal primaria -- Area sem vegetacao"
    df$`Tier 6`[index] <- "non primary forrest vegetation --  area without vegetation"
    index <- df$`Tier 6` == "Vegetacao nao florestal primaria -- Silvicultura"
    df$`Tier 6`[index] <- "non primary forrest vegetation -- silviculture"
    index <- df$`Tier 6` == "Vegetacao nao florestal primaria -- Uso agropecuario"
    df$`Tier 6`[index] <- "non primary forrest vegetation --  agricultural and cattle raising use"
    index <- df$`Tier 6` == "Vegetacao nao florestal primaria --  Vegetacao nao florestal primaria"
    df$`Tier 6`[index] <- "non primary forrest vegetation -- non primary forrest vegetation"
    index <- df$`Tier 6` == "Vegetacao nao florestal secundaria -- Area sem vegetacao"
    df$`Tier 6`[index] <- "non secondary forrest vegetation -- area without vegetation"
    index <- df$`Tier 6` == "Vegetacao nao florestal secundaria -- Silvicultura"
    df$`Tier 6`[index] <- "non secondary forrest vegetation -- silviculture"
    index <- df$`Tier 6` == "Vegetacao nao florestal secundaria -- Uso agropecuario"
    df$`Tier 6`[index] <- "non secondary forrest vegetation -- agricultural and cattle raising use"
    index <- df$`Tier 6` == "Vegetacao nao florestal secundaria -- Vegetacao nao florestal secundaria"
    df$`Tier 6`[index] <- "non secondary forrest vegetation -- non secondary forrest vegetation"
    index <- df$`Tier 6` == "Vinhaca"
    df$`Tier 6`[index] <- "stillage"
    ## Type of emission ##
    index <- df$`Type of emission` == "Emissao"
    df$`Type of emission`[index] <- "emission"
    index <- df$`Type of emission` == "Remocao"
    df$`Type of emission`[index] <- "removal"
    return(df)
  }

  if (language == "eng"){
    colnames(df) <- c("Tier 1", "Tier 2", "Tier 3", "Tier 4", "Tier 5", "Tier 6", "Type of emission",
                    "Gas", "Territory", "Municipality_Code", "Municipality", "Economic_activity", "Product",
                    "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007","2008","2009", "2010",
                    "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019_AREA")
    df <- to_english(df)
  }
  return(df)
}
